---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: placement-api
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: placement-api
    spec:
      initContainers:
        - command:
          - kubernetes-entrypoint
          name: init
          image: {{ include "common.images.kubernetes-entrypoint" (dict "registry" .Values.imageRegistry "namespace" .Values.imageNamespace) | quote }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INTERFACE_NAME
            value: eth0
          - name: DEPENDENCY_JOBS
            value: "placement-db-sync,placement-register"
      containers:
        - name: placement-api
          securityContext:
            privileged: true
          image: {{ template "placement.placement-api.image" . }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          {{- if .Values.enableLivenessProbe }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: 8778
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 15
          {{- end }}
          {{- if .Values.enableReadinessProbe }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: 8778
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 15
          {{- end }}
          env: 
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_SERVICE_NAME
              value: "placement-api"
          ports:
            - name: placement-api
              containerPort: 8778
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/kolla/placement
              name: kollalog
              mountPropagation: HostToContainer
            - name: placement-etc
              mountPath: /var/lib/kolla/config_files/config.json
              subPath: placement-api.json
            - name: placement-etc
              mountPath: /var/lib/kolla/config_files/placement.conf
              subPath: placement.conf
            - name: placement-etc
              mountPath: /var/lib/kolla/config_files/migrate-db.rc
              subPath: migrate-db.rc
            - name: placement-etc
              mountPath: /var/lib/kolla/config_files/placement-api-wsgi.conf
              subPath: placement-api-wsgi.conf
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      volumes:
        - hostPath:
            path: /var/log/kolla/placement
            type: DirectoryOrCreate
          name: kollalog
        - configMap:
            defaultMode: 420
            name: placement-etc
          name: placement-etc

