{{- if .Values.ceph.enabled }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.ceph.serviceAccountName}}
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.ceph.serviceAccountName}}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.ceph.serviceAccountName}}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.ceph.serviceAccountName}}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}

